import React from 'react';

const PracticePage = () => {
    return (
        <div>
            <h1>this is PracticePage</h1>
            <h3>Practice Title 1</h3>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio odit ratione dignissimos quas velit nobis nemo fugit, nihil nisi. In iure aperiam maiores, tenetur laudantium non quaerat corrupti aliquam. Eum itaque culpa dicta. Earum aliquam aut alias quia quam cumque aliquid facilis voluptatem a ea explicabo iure voluptate ipsam, vero, fuga delectus soluta quos autem! Temporibus quia reiciendis ex dolor cupiditate similique optio quis. Molestias in perferendis velit vel blanditiis, incidunt dicta dignissimos maxime, voluptatum facere amet ut repellat aut quo aperiam minima laudantium enim eius ab consequuntur illo! Consequuntur illo, at voluptatibus iusto laborum vero, eos totam corrupti aspernatur nihil provident optio est fugit quae impedit repudiandae reiciendis veniam repellat libero beatae magnam alias, assumenda perferendis placeat. Modi aliquam quibusdam natus id similique magni dolor recusandae eum debitis repellat exercitationem consectetur impedit quod, unde minima quae rerum officia? Esse ut repellendus explicabo, minima at architecto fugit quae debitis quaerat laudantium quibusdam, et nostrum possimus eveniet unde dignissimos necessitatibus doloribus quo molestias quia id ad nesciunt veritatis. Eligendi delectus corrupti aliquid accusantium omnis nesciunt vitae obcaecati laboriosam error dignissimos, consequuntur esse enim maiores neque. Odio, nobis, iure neque minus vitae architecto facere delectus voluptatibus, eveniet cupiditate sapiente distinctio ex inventore!</p>
            <h3>Practice Title 2</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias quia eos quos nam exercitationem similique accusantium consequuntur nisi esse autem, blanditiis voluptate numquam a ratione nulla obcaecati. Non eligendi odio nihil eos pariatur autem dolores iure inventore quisquam iste? Itaque, maxime? Asperiores molestiae illum sunt voluptates neque eaque quisquam, possimus est laboriosam, similique error quae doloribus ullam quam deleniti inventore placeat voluptas. Deleniti nihil, alias maxime quidem veritatis dicta ea aut doloribus! Reprehenderit, natus! Nostrum porro autem impedit dolores ratione culpa quam provident repellendus nobis. Laboriosam, tenetur in. Quibusdam voluptatum velit inventore! Beatae tenetur ad itaque quod ipsa iure nihil?</p>
            <h3>Practice Title 3</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias quia eos quos nam exercitationem similique accusantium consequuntur nisi esse autem, blanditiis voluptate numquam a ratione nulla obcaecati. Non eligendi odio nihil eos pariatur autem dolores iure inventore quisquam iste? Itaque, maxime? Asperiores molestiae illum sunt voluptates neque eaque quisquam, possimus est laboriosam, similique error quae doloribus ullam quam deleniti inventore placeat voluptas. Deleniti nihil, alias maxime quidem veritatis dicta ea aut doloribus! Reprehenderit, natus! Nostrum porro autem impedit dolores ratione culpa quam provident repellendus nobis. Laboriosam, tenetur in. Quibusdam voluptatum velit inventore! Beatae tenetur ad itaque quod ipsa iure nihil?</p>
            <h3>Practice Title 4</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias quia eos quos nam exercitationem similique accusantium consequuntur nisi esse autem, blanditiis voluptate numquam a ratione nulla obcaecati. Non eligendi odio nihil eos pariatur autem dolores iure inventore quisquam iste? Itaque, maxime? Asperiores molestiae illum sunt voluptates neque eaque quisquam, possimus est laboriosam, similique error quae doloribus ullam quam deleniti inventore placeat voluptas. Deleniti nihil, alias maxime quidem veritatis dicta ea aut doloribus! Reprehenderit, natus! Nostrum porro autem impedit dolores ratione culpa quam provident repellendus nobis. Laboriosam, tenetur in. Quibusdam voluptatum velit inventore! Beatae tenetur ad itaque quod ipsa iure nihil?</p>
        </div>

    );
};

export default PracticePage;